version: '3'

services:
  database:
    image: mysql
    hostname: database
    networks:
      - workshop
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456

  wordpress:
      image: wordpress
      networks:
        - workshop
      ports:
        - "8888:80"
      environment:
        WORDPRESS_DB_HOST: database
        WORDPRESS_DB_USER: user
        WORDPRESS_DB_PASSWORD: 123456

networks:
  workshop:
    driver: bridge
